### ISSUE TITLE
Different location for stories then "Documents"

### ISSUE THREAD

**Issue by Lexstok** [klembot/twinejs#1026]
### Is your feature request related to a problem? Please describe.

I'm trying to write some stories, but I use multiple computers for different purposes. I tend to write on my Mac and render content on my Windows PC due to it having an Nvidia card. It would be useful to be able to specify in Twine where to save my stories, so that I can save them in Dropbox for example. 

### Describe the solution you'd like.

Would it be possible to let the user override the default location where the stories are saved and specify their own base location ?

### Describe alternatives you've considered.

Writing a script to regularly copy and sync between folders. Tried using an alias on Mac, but Twine does not consider an alias to the Stories folder a real folder...

### Additional context on this suggestion.

Could not find other people asking for this.

### Presubmission checklist

- [ ] I am interested in working on code that would implement this feature request. (This is not required to submit a suggestion.)
- [X] I have done a search and believe that an issue does not already exist for this idea in the GitHub repository.
- [X] I have read and agree to abide by this project's Code of Conduct.

**Comment by greyelf** [comment]
@Lexstok 
> Tried using an alias on Mac, but Twine does not consider an alias to the Stories folder a real folder

While you wait try replacing the Twine 2.x application's **Stories** folder with [a Symbolic Link to the alternative folder](https://www.switchingtomac.com/tutorials/osx/how-to-create-symlinks-on-your-mac/), instead of an Alias/Shortcut.

**Comment by Lexstok** [comment]
I always assumed that an alias and a symlink were the same thing - thanks for pointing out to me that these are *not* the same, it now works as expected ! Thanks !
Found some more explanations on this as well: https://www.oreilly.com/library/view/mac-os-x/0596004605/ch01s10.html
