### ISSUE TITLE
Test, Play, and Publish not working in Twine 2.4.1 with Snowman 2.0.2

### ISSUE THREAD

**Issue by ludologue** [klembot/twinejs#1225]
### Describe the bug.

Though "Test from Here" from Passage works and the story performs as designed, three options on the Build menu, Test, Play, and Publish to File, do not work.  Browser does not open for Test/Play, file-save window does not open for Publish.  No error messages.  Code of the single passage in the story is attached as text (can't export html file).  

Browser is Chrome Version 103.0.5060.134 (Official Build) (64-bit), running on Windows 11.

[Failed_Snowman_Code.txt](https://github.com/klembot/twinejs/files/9202889/Failed_Snowman_Code.txt)
.

### Steps to reproduce:

Create new story with Snowman 2.0.2 format, paste in code from text file.  Try Test, Play, and Publish.

### Expected behavior:

Expected Chrome to open for Test and Play operations.  Expected Windows file-save dialog to open for Publish.

### Additional context on this problem.

At first I suspected I might be using the "visited()" function improperly -- it does indeed fail if the story format is not 2.0.2 -- but I can't see a problem.

### Twine version number

2.4.1

### Does this problem occur with the web version of Twine or the desktop app?

Desktop app

### What operating system does this problem occur on?

Windows

### Presubmission checklist

- [ ] I am interested in working on code that would fix this bug. (This is not required to submit a bug report.)
- [X] I have done a search and believe that an issue does not already exist for this bug in the GitHub repository.
- [X] I have read and agree to abide by this project's Code of Conduct.

**Comment by mcdemarco** [comment]
This (build, play, and publish) ran normally for me on MacOS (Big Sur), same Twine version, in the desktop version.  The code is:

```
<%
s.adjs = ['green','vast','soggy','smiling','full of monkeys'];
if(visited("Snowflakes") == 1){
	s.thisPick = "";
    s.prevPick = "";
}
while(s.thisPick == s.prevPick){
	s.thisPick = s.adjs[Math.floor(Math.random()*s.adjs.length)]
}
s.prevPick = s.thisPick
%>

The sky above is [[<%=s.thisPick%> ->Snowflakes]].
```

**Comment by ludologue** [comment]
Yeah, sorry, this was probably something really stupid I did with the JavaScript at some point.  It runs fine for me, too, in a fresh story.

 

Thanks for your time,

 

Stuart
