### ISSUE TITLE
Installed Twine 2.5.1.0 SugarCube set to default but only resets to Harlowe when published

### ISSUE THREAD

**Issue by jonboy075** [klembot/twinejs#1313]
### Describe the bug.

After installing twine 2.5.1.0 on to windows 10 PC I set the default story format to sugarcube.

I build a small story and publish it for testing only to find that the sugarcube code returns an error. 

Harlowe macros use a different syntax to Twine 1, SugarCube, and Yarn macros.

The published story has been published in Harlowe and not Sugarcube.

Do you have a fix for this error?
![Screenshot 2022-10-27 at 12-19-22 Survivors](https://user-images.githubusercontent.com/116806439/198271297-4e6c8bef-f232-4443-9eaa-75e82638202b.png)

### Steps to reproduce:

The code below should build a speech box with a character image to the left.

<pre><code><nowiki><<character 'hero' 'Cast/hero.jpg'>></nowiki></code></pre>

Opening the folder on the tablet displays a simple character profile form. 
. 
<<hero>>Aa, finally the council is assembled.<</hero>>

### Expected behavior:

From the above picture i was expecting sugarcube based speech box to show the hero image and the text of the story. but as the published file keeps resetting to harlowe i continue to get the above error.   

### Twine version number

2.5.10

### Does this problem occur with the web version of Twine or the desktop app?

Desktop app

### What operating system does this problem occur on?

Windows

### Presubmission checklist

- [ ] I am interested in working on code that would fix this bug. (This is not required to submit a bug report.)
- [X] I have done a search and believe that an issue does not already exist for this bug in the GitHub repository.
- [X] I have read and agree to abide by this project's Code of Conduct.

**Comment by greyelf** [comment]
Did you create your test Story project **before** or **after** setting the Default Story Format of the Twine application?

I ask because changing the Default Story Format of the Twine application does not update the assigned Story Format of an existing Story project.

**Comment by jonboy075** [comment]
After deleting the project building a new one after setting story format to sugarcube it now works. Thank greyelf for the help. I think I got stuck in a loop when I read a old issue that sounded the same as my issue. 

thank you
