### ISSUE TITLE
Debug Panel: "Record expression replays" is on by default, makes testing slow

### ISSUE THREAD

**Issue by sternfuchs** [klembot/twinejs#1329]
### Describe the bug.

The debug panel (when testing a story) makes the testing slow:
When opening a new passage, it needs about 1000ms, until links in a newly reached passage react to a mouse-click. 
This is too slow for frequent testing needs, inconvenient for anybody with a large story.

### Steps to reproduce:

- Create a Story with 300 passages and 35000 words, 290 variables (99% of variables are basic types, no arrays or datamaps).
- Start testing from any passage.
- Follow a link to a new passage.
Then: You can click on links, but it needs about 1 full second (or more) until the browserpage reacts.

### Expected behavior:

The default behaviour should be the fast one.
Users should be able to choose their personal default behaviour.

Which means:
1. "Record expression replays" should be off by default.
2. The "settings" of the debug panel need to be able to be set in the main application for all future test starts. 
    (Currently these can be set only in the debug panel.)

### Additional context on this problem.

Large story: 300 passages, 35000 words, 290 variables (99% of variables are basic types, no arrays or datamaps).

### Twine version number

2.5.1

### Does this problem occur with the web version of Twine or the desktop app?

Desktop app

### What operating system does this problem occur on?

Windows

### Presubmission checklist

- [ ] I am interested in working on code that would fix this bug. (This is not required to submit a bug report.)
- [X] I have done a search and believe that an issue does not already exist for this bug in the GitHub repository.
- [X] I have read and agree to abide by this project's Code of Conduct.

**Comment by sternfuchs** [comment]
One could discuss, if this is an "enhancement" or a "bug".
But from my experience: I often start multiple tests in a minute. Re-setting the debug panel behaviour with every new test start costs so much time, that I consider it a usability bug.

**Comment by greyelf** [comment]
@sternfuchs 
If I understand correctly you are talking about how a project built with a specific Story Format behaves when you used the **Build** > **Test** option or the **Passage** > **Test From Here** option of the Twine 2.x application to start a Debug session.

If the above is true then you need to know that each Story Format is responsible of implementing its own Debug system, and you will need to contact the Developer of the specific Story Format you are using to let them know of the issue you are having. 

The following links are for the Issues page of each of the main Story Formats.
[Harlowe Issues](https://foss.heptapod.net/games/harlowe/-/issues).
[SugarCube Issues](https://github.com/tmedwards/sugarcube-2/issues)
[Chapbook Issues](https://github.com/klembot/chapbook/issues)
[Snowman Issues](https://github.com/videlais/snowman/issues)

**Comment by sternfuchs** [comment]
@greyelf Thank you very much for the hint!
That of course somehow makes sense, but I wasn't aware of it.
