### ISSUE TITLE
Twine Crashes when closing a passage with find open

### ISSUE THREAD

**Issue by david-donachie** [klembot/twinejs#1396]
### Describe the bug.

While using Twine desktop app, with a story open, I experienced a crash.

I had one passage open, and the find/replace box. I closed the passage, and got the following crash.

```
Something went wrong and Twine can't continue.

Please try restarting Twine or reloading the page.

If you see this message repeatedly, please [report a bug](https://twinery.org/2bugs).

Details:

Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at nl (file:///Applications/Twine.app/Contents/Resources/app.asar/electron-build/renderer/static/js/2.333a9c1b.chunk.js:2:636765)
    at ba (file:///Applications/Twine.app/Contents/Resources/app.asar/electron-build/renderer/static/js/2.333a9c1b.chunk.js:2:608664)
    at file:///Applications/Twine.app/Contents/Resources/app.asar/electron-build/renderer/static/js/2.333a9c1b.chunk.js:2:265437
    at file:///Applications/Twine.app/Contents/Resources/app.asar/electron-build/renderer/static/js/2.333a9c1b.chunk.js:2:265585
    at file:///Applications/Twine.app/Contents/Resources/app.asar/electron-build/renderer/static/js/main.a1ceacd6.chunk.js:1:101321
    at file:///Applications/Twine.app/Contents/Resources/app.asar/electron-build/renderer/static/js/2.333a9c1b.chunk.js:2:265578
    at file:///Applications/Twine.app/Contents/Resources/app.asar/electron-build/renderer/static/js/main.a1ceacd6.chunk.js:1:120619
    at file:///Applications/Twine.app/Contents/Resources/app.asar/electron-build/renderer/static/js/main.a1ceacd6.chunk.js:1:91377
    at ls (file:///Applications/Twine.app/Contents/Resources/app.asar/electron-build/renderer/static/js/2.333a9c1b.chunk.js:2:629623)
    at Ol (file:///Applications/Twine.app/Contents/Resources/app.asar/electron-build/renderer/static/js/2.333a9c1b.chunk.js:2:648512)
```

### Steps to reproduce:

I tried this on another story, and got exactly the same behaviour. Closing an already-open passage editor while the find box was opened crashes every time. Doing this in the other order (opening find, searching, and then opening and closing an editor) does not crash.

The crash does not happen if the search matches no passages, but does happen whether or not the matched passage is the open one.

I also had 4 or 5 other people test the crash in various versions and it happens in all of them.

### Expected behavior:

Twine should not crash

### Additional context on this problem.

I've marked this for Desktop, but the same happens in twinery.org 

### Twine version number

2.6.1

### Does this problem occur with the web version of Twine or the desktop app?

Desktop app

### What operating system does this problem occur on?

macOS

### If this problem is occurring with the web version of Twine, what browser does it occur on?

None

### Presubmission checklist

- [ ] I am interested in working on code that would fix this bug. (This is not required to submit a bug report.)
- [X] I have done a search and believe that an issue does not already exist for this bug in the GitHub repository.
- [X] I have read and agree to abide by this project's Code of Conduct.

**Comment by Mercy-R-Duval** [comment]
what do you mean?
