### ISSUE TITLE
Creating CSS styling for tables changes the way that the testing environment appears.

### ISSUE THREAD

**Issue by marti-toonen** [klembot/twinejs#1422]
### Describe the bug.

I'm using Harlowe, and I created a table to display particular variables. I began testing the game after creating these tables (and their subsequent styles in CSS) and found that rather than displaying in a neat list as usual, the testing environment that displays variables and their values was adjusted to display horizontally, making it nearly impossible to read. 

This had occurred in my other Twine files as well, but this one was nearly new and had been displaying properly before: I only just put together now that I use the tables in other files as well, and so I deleted the CSS styling for tables and relaunched the testing environment to find everything displaying correctly.

### Steps to reproduce:

Creating custom CSS for 'table' seems to mess things up the worse, whereas custom styles for 'th' and 'tr' do make things look strange, it doesn't have as strong an effect. I'll paste my CSS code (which was just WIP style I applied) below.

`table {
  width: 50%;
  display: flex;
  flex-flow: row nowrap;
  justify-content: flex-start;
  align-content: center;
}
	tr, th {
      min-width: 30%;
      display: flex;
      flex-flow: row nowrap;
      justify-content: center;
      align-content: center;
	}`

### Expected behavior:

I didn't expect that something I adjusted in the CSS for my story would have any effect on the testing environment itself, and so when I launched I expected to see the testing environment as usual, with my variables laid out in a readable list as they usually would be.

### Additional context on this problem.

This is fine to work around, but makes me wonder if the CSS for individual stories could have more effect on the testing environment in a way I just haven't come across yet.

### Twine version number

2.7.0.0

### Does this problem occur with the web version of Twine or the desktop app?

Desktop app

### What operating system does this problem occur on?

Windows

### If this problem is occurring with the web version of Twine, what browser does it occur on?

None

### Presubmission checklist

- [ ] I am interested in working on code that would fix this bug. (This is not required to submit a bug report.)
- [X] I have done a search and believe that an issue does not already exist for this bug in the GitHub repository.
- [X] If this problem is occurring with the app version of Twine, it still happens after I remove the `user.css` file from my Twine folder. (You would've added this file yourself. If you don't understand this question, you can safely check this box.)
- [X] I have read and agree to abide by this project's Code of Conduct.

**Comment by greyelf** [comment]
@marti-toonen 
Each of the Story Formats are responsible for implementing their own "test/debug" mode, all the Twine 2.x application itself does is let the Story Format know that one of the "test"" related options has been selected.

In the case of Harlowe 3.x, its runtime engine adds a `<tw-debug>` element (along with its content) to the web-page's Document Object Model (DOM), just before/above the `<tw-story>` element that represents the main "story" area of the page.

So if you want your custom "table" related CSS to only target tables that appear within that main "story" area then you need to add the **tw-story** element-type to the CSS Selectors like so...
```
tw-story table {
	width: 50%;
	display: flex;
	flex-flow: row nowrap;
	justify-content: flex-start;
	align-content: center;
}

tw-story tr, tw-story th {
	min-width: 30%;
	display: flex;
	flex-flow: row nowrap;
	justify-content: center;
	align-content: center;
}
```

**Comment by marti-toonen** [comment]
Ah, I see! Thanks for the explanation!
