### ISSUE TITLE
Twine 2.2.1 - Harlowe 2.1.0 - (link-reveal:) and (enchant: ?link) causing problems.

### ISSUE THREAD

**Issue by M3tav0X** [klembot/twinejs#515]
I made a text adventure game for a project in my Fall 2018 semester of Uni. Overall, my professor liked the final product and wants me to enter the game into the English Colloquium this Spring. In preparation for this, while I had some free-time today, I decided to run though the game a bit and see if anything needed any fine-tuning or improvements.

During a test run through the game, I ran into a strange issue in one of the later passages of the game; any link using the (link-reveal:) macro wouldn't execute to reveal the next bit of text, meaning that any player unlucky enough to get to that passage would be stuck and have nowhere to go. After a while of investigating and much trial-and-error, I discovered that the point of issue was a command macro I put in place to change the color of the link text.

All but one passage in this game has either a black background with white text and blue links **OR** a white background with black text and red links. The backgrounds of the passages are display whether the location is either "dark" (the black background) or "lit" (the white background). 

"Lit" pages each use two different (enchant:) command macros; (enchant: ?page, (text-colour: black) + (background: white)) sets the background and text color for the entire page, and (enchant: ?link, (text-colour: red)) sets the text color of all links in the passage to red. Now, it's important to note that without the (enchant: ?link, (text-colour: red)) command, the links work perfectly fine. My reason for adding this particular command macro is because after the (enchant: ?page, (text-colour: black) + (background: white)), _all_ text on the page - including links - is set to the color black, so links would blend-in with the regular text.

While I haven't gotten to checking them out yet, there are a few other "lit" passages with (link-reveal:) macros in my game and I'm willing to bet that they have the same issue right now. I didn't notice this problem earlier because I designed the game to have a _very_ high degree of randomness, so given that the (link-reveal:) macro is only utilized in a small handful of passages, the likelihood of my running into this issue was _very_ small in most of the game.

Is there any way for me to work around this without completely omitting the (enchant: ?link, (text-colour: red)) command from the game? I'd really like to keep the links in the "lit" passages red of at all possible. 

If anyone wants to try fiddling around with the macros for themselves or try out the game or whatever else, then at the bottom of this post, I'm including a zip file that contains two HTML files; an archive file for Twinery that can be used to import the game and a published file of the game that can be used to play it as is. If anyone can offer any sort of advice or assistance I would really appreciate it! 

Thank you all in advance!!

ZIP File Download: [M3tav0X -Trash King!! HTML Files (ZIPPED).zip](https://github.com/klembot/twinejs/files/2739586/M3tav0X.-Trash.King.HTML.Files.ZIPPED.zip)

**Comment by greyelf** [comment]
@M3tav0X 
The bug you're describing is in the Harlowe v2.x story format's engine not the Twine 2.x application itself, this means you should be reporting it on [that story format's repository](https://bitbucket.org/_L_/harlowe/src/default/).

It should be noted that the yet to be released Harlowe v3.0 contains a fix that allows the following example to work correctly.
```
(link-reveal: "Link Text")[
	Some content to reveal.
]
(enchant: ?page, (text-colour: black) + (background: white))
(enchant: ?link, (text-colour: red))
```
