### ISSUE TITLE
Twine 2.2.1/SugarCube 2.28.2 / Opera 58.0.3135.53  fails: no storage adapter 

### ISSUE THREAD

**Issue by selden** [klembot/twinejs#519]
Twine 2.2.1 / SugarCube 2.28.2 / Opera 58.0.3135.53 / Win7 Pro X64
A minimal story won't run under the current version of Opera. It generates a fatal error popup which complains

Error: no valid storage adapters found.

![opera failure](https://user-images.githubusercontent.com/353932/52342522-a5f32080-29e3-11e9-9181-738197b079c4.png)

I've attached a zip containing the minimal html published by Twine which generates this error.
It works fine with other browsers, so I consider this low priority.

[opera-no storage.zip](https://github.com/klembot/twinejs/files/2836385/opera-no.storage.zip)

**Comment by greyelf** [comment]
This may be more of a SugarCube 2.x issue than a Twine 2.x one.

I suggest reporting this error on the [SugarCube repository](https://bitbucket.org/tmedwards/sugarcube/issues?status=new&status=open).

**Comment by selden** [comment]
Thanks for the suggestion! 

I've reported the Opera problem there. Apparently it's a side effect of disabling 3rd party cookies.
