### ISSUE TITLE
Old link in "report a bug"

### ISSUE THREAD

**Issue by EleXte** [klembot/twinejs#542]
I'm not sure this is bug or feature but it's realy looks wrong.
![Screenshot_98](https://user-images.githubusercontent.com/18257611/55913811-2dc8f700-5bee-11e9-965c-e5de83a9a5da.png)
This actualy to version 2.3.0-b2

Forgot one moment. When this page open you can't return back. Need restart Twine to contine working.

**Comment by hogart** [comment]
There's still old link in "About" window, right here: https://github.com/klembot/twinejs/blob/develop/src/dialogs/about/index.html#L35
