### ISSUE TITLE
Append linked passages to the current page?

### ISSUE THREAD

**Issue by derekchiang** [klembot/twinejs#578]
Hi, I'm fairly new to Twine/Harlowe so I hope I'm not missing something obvious.

Right now, when you click on a link text, you are directed to a new page with the new passage.

What I'm trying to achieve, is that when a reader clicks on a link text, that the new passage is simply *appended* to the current page.  As such, the reader would be able to see 1) the entirety of the text they've read so far, and 2) the choices they have made so far.

Is that achievable with Twine/Harlowe?

**Comment by derekchiang** [comment]
After some more googling I've found the answer.  Basically you wanna install this plugin: http://www.mcdemarco.net/tools/scree/paloma/

**Comment by phivk** [comment]
I see you have also discovered the Trialogue story format already, but wanted to add it here for reference. It's based on Paloma and heavily restyled to create a conversational chat interface.

In case that is what you're looking for, see the readme for more details:

https://github.com/phivk/trialogue
