### ISSUE TITLE
Twine 2.3.5 exe fails install on Win 10

### ISSUE THREAD

**Issue by mpvenables** [klembot/twinejs#621]
The latest version of Twine fails to install on Windows 10.

**To Reproduce**
1. Download .exe file.
2. R-click and select "Run as administrator"

**Expected behavior**
Installation of .exe file.

**Screenshots**
N/A

** App version **
2.3.5

** Environment **
Win 10 Home x64 Build 1803.

**Comment by mpvenables** [comment]
[twine_2.3.5_win.exe_install failure.txt](https://github.com/klembot/twinejs/files/3786392/twine_2.3.5_win.exe_install.failure.txt)

**Comment by mpvenables** [comment]
Attached log for install failure.

**Comment by HiEv** [comment]
I took a quick look at the "twine_2.3.5_win.exe_install failure.txt" log, and it has errors dating back to 8/20/2019, but I didn't see anything that looked like a Twine installer error within it.

**Comment by mpvenables** [comment]
Apologies for the ancient reply. Thanks for taking a look. I'll check it out on my other Win laptop.
