### ISSUE TITLE
The toggle UI icon merely closes the UI bar

### ISSUE THREAD

**Issue by Jaydax1729** [klembot/twinejs#646]
The toggle UI icon closes the UI bar but doesn't remain visible to re-open it.
I'm using Twine version 2.3.5 and Sugarcube 2.30.0
Browser is Google Chrome.
The UI bar can be made to re-appear by refreshing the window but this won't work on a tablet or phone which doesn't offer refresh. This makes using a small screen device very difficult.

**Comment by Jaydax1729** [comment]
Well I have a work around:
To your CSS add:
.fixedbr {
  transform: scaleX(0.5);
  position: fixed;
    top: 10px;
    left: 1px; 
} 
At the end of each passage add (especially after any <</if>> statements:
 <span class="fixedbr"><<link ">">><<run UIBar.unstow() >><</link>></span>

This will add a '>' at the top left of your page. Clicking that will open the sidebar and cover it. You can use the sidebar's '<' to close it.

**Comment by HiEv** [comment]
FYI - That wasn't a Twine issue, it was a SugarCube issue.
SugarCube issues should be posted here:
[https://github.com/tmedwards/sugarcube-2/issues](https://github.com/tmedwards/sugarcube-2/issues)
