### ISSUE TITLE
"Expected expression, got keyword 'in'"

### ISSUE THREAD

**Issue by Hirmumyrsy** [klembot/twinejs#653]
Using Harlowe 3.1.0.
The very same phrase that's used on https://twine2.neocities.org/#macro_history doesn't work for me: (history: where "x" is not in its name) results in an error saying "expected expression, got keyword 'in'". I have tried copypasting the very code from the site to a clean passage, so I haven't typed it wrong. It seems not to recognise that one can give such a command at all.

**To Reproduce**
1. try getting an array out of (history: where "x" is not in its name), where "x" is a passage you have (or don't have).
2. See error

**Expected behavior**
The command should give an array of visited passage names, excluding passages whose name contains "x" anywhere in it.

** App version **
Twine 2.3.7, Harlowe 3.1.0

** Environment **
- Windows 10 64-bit

**Additional context**
I'm trying to use this to go back to the last passage that doesn't have "inventory" in its name (exiting a complex inventory system in this case, to be precise). Is there a better way to accomplish this? (history:)'s last doesn't work.

**Comment by HiEv** [comment]
This wouldn't be a Twine issue, it would be a Harlowe issue.

[Harlowe issues should be reported here](https://bitbucket.org/_L_/harlowe/issues?status=new&status=open).
