### ISSUE TITLE
URGENT: Passage stuck on the side 

### ISSUE THREAD

**Issue by WmXaxp** [klembot/twinejs#792]
I don't know what happen. Everything was going fine until some of my passages started to unlink and when I tried to move a new one, it was created inside the same passage on the screen... And I cant move.... the others started to move by itself, and when I create now, It stucks on the left side of the screen... I cant move.... but the program works fine..

**Comment by WmXaxp** [comment]
It's urgent. I have to deliver the the script today :(((( 

I tried to close and reopen, but it doesnt change

**Comment by HiEv** [comment]
Sorry I didn't see your comment earlier, but this is likely related to the "[Story files with malformed positions aren't handled gracefully](https://github.com/klembot/twinejs/issues/591) #591" bug and the related fix you can use.
