### ISSUE TITLE
Non minified format.js 

### ISSUE THREAD

**Issue by Elefrea** [klembot/twinejs#863]
Hello, 

I would like to add some features to the SugarCube theme, but the format.js file is minified.
Is it possible to find a non minified version somewhere ?

**Comment by greyelf** [comment]
@Elefrea 
If your after a copy of the SugarCube story format template that isn't embedded within the Twine 2.x application then you may want to look on the [SugarCube repository](https://github.com/tmedwards/sugarcube-2) instead.
