### ISSUE TITLE
(click:?page) triggered when entering node

### ISSUE THREAD

**Issue by henning101** [klembot/twinejs#864]
Hi everyone! I would like to use ```(click: ?page)[==``` macros to show dialog text one by one. However, the first ```(click: ?page)[==``` is already triggered when entering the node.

A hackish "fix" is to simply put a ```(click: ?page)[==``` on top to catch the phantom click but this is probably not really a stable solution.

Is there a way to fix this?

**Comment by greyelf** [comment]
@henning101 
This Issues section is for reporting problems with or requesting enhancements to the Twine 2.x application itself, not for asking for help with any of the Story Formats that come pre-installed with the application.

There are a number of sites that are dedicated to answering Twine related "how do I" type questions:
1. The [Twine Games](https://discordapp.com/invite/n5dJvPp) Discord server.
2. The Twine section of [The Interactive Fiction Community Forum](https://intfiction.org/).
3. [The home of Twine games on Reddit](https://www.reddit.com/r/twinegames/)

That being said, I created a simple test Harlowe v3.2.2 project with the following code within the project's initial Passage, and it worked correctly. 
eg. No text was shown until I clicked on the page, and the second line of text only appeared after I clicked on the page a 2nd time.
```
(click: ?Page)[==
First blah blah
(click: ?Page)[==
Second blah blah
```
I suggest you ask your question again on one of the above listed sites.

**Comment by henning101** [comment]
Ok thank you I will post the question there! The error occurs only when you transition from one passage to another (I should have mentioned that). My guess is that the click from the origin passage of the transition somehow registers for the destination passage.
