### ISSUE TITLE
Passages arent connecting

### ISSUE THREAD

**Issue by sasayakita** [klembot/twinejs#968]
hi! i just discovered twine by a programming class but im having an issue, the passages arent connecting!
![2021-11-23](https://user-images.githubusercontent.com/94933494/143114776-716181c2-aa37-4021-93e2-953a01e36f7f.png)
![2021-11-23 (1)](https://user-images.githubusercontent.com/94933494/143114935-1ed9edd5-3fb3-4179-8a70-3f5ac313371b.png)
can someone help me? i would apreciate a lot 
ps: english isnt my main language so if something is wrong here pls dont mind xD

**Comment by greyelf** [comment]
If the last line in your example is meant to be a Markup based link then you need to replace the Curly Braces (brackets) you are using with Square Brackets.
eg. Change...
```
{{Inicio.}}
```
...to be...
```
[[Inicio.]]
```

note: Harlowe uses Curly Braces to indicate the usage of [Collapsing whitespace markup](https://twine2.neocities.org/#markup_collapsing-whitespace).

**Comment by sasayakita** [comment]
ohhh thank you!!! <3
